services:
  - type: web
    name: aikya-foundation
    runtime: node
    rootDir: aikya-website
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
