services:
  - type: web
    name: aikya-foundation
    runtime: node
    rootDir: aikya-website
    buildCommand: cd aikya-website && npm install && npm run build
    startCommand: cd aikya-website && npm start
    envVars:
      - key: NODE_ENV
        value: production
